const { Client, LocalAuth, MessageMedia } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');
const axios = require('axios');

// OrbitX_bot Configuration
const client = new Client({
    authStrategy: new LocalAuth(),
    puppeteer: {
        headless: true,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--single-process'
        ],
        executablePath: '/usr/bin/chromium' // Koyeb/Docker ke liye zaroori hai
    }
});

const CONFIG = {
    AI_URL: 'https://api.longcat.chat/openai/v1/chat/completions',
    AI_KEY: 'ak_1Ea5cx4AQ2Nu67s39u0YL4Hh6WK3W',
    REMOVE_BG_KEY: 'o247jVzLehQQxeaUby3EjezA',
    WEATHER_KEY: 'c2b6b0ca5acc9229fe76d54e9e355164',
    NEWS_KEY: 'df886c07f4aa44a68a47f56d1251038b',
    RAPID_API_KEY: '6d3cbf2273msha3bd4f088bf802cp1d4630jsn954fe763e089',
    EXCHANGE_KEY: 'c6ded9e6074d57bd28b1b3f8'
};

client.on('qr', (qr) => {
    qrcode.generate(qr, { small: true });
    console.log('OrbitX_bot: Scan this QR Code now!');
});

client.on('ready', () => {
    console.log('OrbitX_bot is online and ready!');
});

client.on('message', async (msg) => {
    const text = msg.body.toLowerCase();
    const args = text.split(' ').slice(1).join(' ');

    // 1. MENU COMMAND
    if (text === '.menu' || text === '.help') {
        let menu = `*🌐 OrbitX_bot - All-in-One Utility*\n\n` +
                   `*🤖 AI & Chat:* \n.ai [query]\n\n` +
                   `*🖼 Image Tools:*\n.sticker (send image with caption)\n.qr [link]\n\n` +
                   `*📥 Downloader:*\n.dl [link] (YT, FB, IG, TT)\n\n` +
                   `*🌍 Info Tools:*\n.weather [city]\n.news\n.convert [amount] [from] [to]\n\n` +
                   `*🛠 Utilities:*\n.calc [math]\n.passgen\n\n` +
                   `_OrbitX_bot: Developed for convenience!_`;
        msg.reply(menu);
    }

    // 2. AI CHAT (LongCat API)
    if (text.startsWith('.ai ')) {
        try {
            const response = await axios.post(CONFIG.AI_URL, {
                model: "gpt-4o",
                messages: [{ role: "user", content: args }]
            }, { headers: { 'Authorization': `Bearer ${CONFIG.AI_KEY}` } });
            msg.reply(response.data.choices[0].message.content);
        } catch (e) { msg.reply("AI Error: Could not connect to OrbitX engine."); }
    }

    // 3. WEATHER
    if (text.startsWith('.weather ')) {
        try {
            const res = await axios.get(`https://api.openweathermap.org/data/2.5/weather?q=${args}&appid=${CONFIG.WEATHER_KEY}&units=metric`);
            const weatherInfo = `📍 *City:* ${res.data.name}\n🌡️ *Temp:* ${res.data.main.temp}°C\n☁️ *Status:* ${res.data.weather[0].description}`;
            msg.reply(weatherInfo);
        } catch (e) { msg.reply("City not found."); }
    }

    // 4. DOWNLOADER (RapidAPI)
    if (text.startsWith('.dl ')) {
        msg.reply("OrbitX is fetching your video... please wait.");
        try {
            const res = await axios.post('https://social-media-video-downloder.p.rapidapi.com/apidownload', 
            { url: args, plt: "auto" }, 
            { headers: { 'x-rapidapi-key': CONFIG.RAPID_API_KEY, 'Content-Type': 'application/json' } });
            msg.reply(`Download Link: ${res.data.url}`);
        } catch (e) { msg.reply("Download failed. Link check karen."); }
    }

    // 5. CURRENCY CONVERTER
    if (text.startsWith('.convert ')) {
        const parts = args.split(' ');
        if(parts.length < 3) return msg.reply("Usage: .convert 100 usd pkr");
        try {
            const res = await axios.get(`https://v6.exchangerate-api.com/v6/${CONFIG.EXCHANGE_KEY}/pair/${parts[1]}/${parts[2]}/${parts[0]}`);
            msg.reply(`💰 ${parts[0]} ${parts[1].toUpperCase()} = ${res.data.conversion_result} ${parts[2].toUpperCase()}`);
        } catch (e) { msg.reply("Conversion error."); }
    }

    // 6. STICKER MAKER
    if (msg.hasMedia && text === '.sticker') {
        const media = await msg.downloadMedia();
        client.sendMessage(msg.from, media, { sendMediaAsSticker: true, stickerAuthor: "OrbitX", stickerName: "BotPack" });
    }

    // 7. QR GENERATOR
    if (text.startsWith('.qr ')) {
        const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encodeURIComponent(args)}`;
        const media = await MessageMedia.fromUrl(qrUrl);
        client.sendMessage(msg.from, media, { caption: `QR Code generated by OrbitX` });
    }

    // 8. PASSWORD GENERATOR
    if (text === '.passgen') {
        const pass = Math.random().toString(36).slice(-10);
        msg.reply(`Generated Secure Password: *${pass}*`);
    }

    // 9. MATH CALCULATOR
    if (text.startsWith('.calc ')) {
        try {
            const result = eval(args); // Simple eval for now
            msg.reply(`OrbitX Result: ${result}`);
        } catch (e) { msg.reply("Invalid Calculation."); }
    }
});

client.initialize();
